apiVersion: "cis.f5.com/v1"
kind: VirtualServer
metadata:
  name: app2-hostgroup-vs
  labels:
    f5cr: "true"
spec:
  host: app1.f5demo.local
  virtualServerAddress: "10.1.10.100"
  virtualServerName: "hostgroup-vs"  
  hostGroup: "apps"
  pools:
    - path: /
      service: app1-svc
      servicePort: 8080
---
apiVersion: "cis.f5.com/v1"
kind: VirtualServer
metadata:
  name: app2-hostgroup-vs
  labels:
    f5cr: "true"
spec:
  host: app2.f5demo.local
  virtualServerAddress: "10.1.10.100"
  virtualServerName: "hostgroup-vs"  
  hostGroup: "apps"
  pools:
    - path: /
      service: app2-svc
      servicePort: 8080