apiVersion: cis.f5.com/v1
kind: VirtualServer
metadata:
  labels:
    f5cr: "true"
  name: reencrypt-tls-vs
  namespace: nginx
spec:
  host: reencrypt.f5demo.local
  tlsProfileName: reencrypt-tls
  virtualServerAddress: 10.1.10.122
  virtualServerName: "reencrypt-tls-vs"
  pools:
  - path: /
    service: nginx-plus
    servicePort: 443
